### ISSUE TITLE
mysql

### ISSUE THREAD

**Issue by fzxiehui** [fzxiehui/worker_notes#11]
```yml
version: '3'

services:
  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    container_name: appmysql
    restart: always
    command: mysqld --default-time-zone=Asia/Shanghai
```
